name: SimpleCI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Test
    runs-on: ubuntu-latest
    environment:
      name: Publish
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies ..."
          pnpm i
      - name: Run Lint Test
        run: |
          echo "Running Linting tests ..."
          pnpm run lint
        env:
          CI: true

  build:
    name: Build Test
    environment:
      name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies ..."
          pnpm i
      - name: Run Building
        env:
          CI: true
          NEXT_PUBLIC_microCMS_SERVICEDOMAIN: ${{secrets.NEXT_PUBLIC_MICROCMS_SERVICEDOMAIN}}
          NEXT_PUBLIC_microCMS_APIKEY: ${{secrets.NEXT_PUBLIC_MICROCMS_APIKEY}}
        run: |
          echo "Running Linting tests ..."
          pnpm run build
